package watermark

import (
	"bytes"
	"compress/zlib"
	"encoding/binary"
	"hash/crc32"
	"image"
	"image/color"
	"image/jpeg"
	"image/png"
	"testing"
)

func pngChunk(typ string, payload []byte) []byte {
	b := make([]byte, len(payload)+12)
	binary.BigEndian.PutUint32(b, uint32(len(payload)))
	copy(b[4:], typ)
	copy(b[8:], payload)
	binary.BigEndian.PutUint32(b[len(b)-4:], crc32.ChecksumIEEE(b[4:len(b)-4]))
	return b
}

func sampleImage() image.Image {
	im := image.NewNRGBA(image.Rect(0, 0, 16, 16))
	for y := 0; y < 16; y++ {
		for x := 0; x < 16; x++ {
			im.SetNRGBA(x, y, color.NRGBA{uint8(x * 16), uint8(y * 16), 100, 255})
		}
	}
	return im
}

func TestPNGMetadataLossless(t *testing.T) {
	var encoded bytes.Buffer
	if err := png.Encode(&encoded, sampleImage()); err != nil {
		t.Fatal(err)
	}
	base := encoded.Bytes()
	var compressed bytes.Buffer
	z := zlib.NewWriter(&compressed)
	z.Write([]byte("Claude"))
	z.Close()
	for _, chunk := range [][]byte{pngChunk("caBX", []byte("jumb c2pa")), pngChunk("tEXt", []byte("Software\x00ChatGPT")), pngChunk("zTXt", append([]byte("Software\x00\x00"), compressed.Bytes()...)), pngChunk("iTXt", append([]byte("Software\x00\x01\x00\x00\x00"), compressed.Bytes()...))} {
		input := append(append(bytes.Clone(base[:len(base)-12]), chunk...), base[len(base)-12:]...)
		out, r, err := Process("photo.png", input, Options{})
		if err != nil {
			t.Fatal(err)
		}
		if !r.WouldChange || len(r.Findings) != 1 || !bytes.Equal(out, base) {
			t.Fatalf("image data not restored verbatim: %+v", r)
		}
		if _, err := png.Decode(bytes.NewReader(out)); err != nil {
			t.Fatal(err)
		}
	}
	for _, s := range []string{"Description\x00Claude Monet", "Software\x00ImageMagick", "Comment\x00Ordinary caption"} {
		input := append(append(bytes.Clone(base[:len(base)-12]), pngChunk("tEXt", []byte(s))...), base[len(base)-12:]...)
		out, r, err := Process("photo.png", input, Options{})
		if err != nil || r.WouldChange || !bytes.Equal(input, out) {
			t.Fatalf("removed benign metadata: %+v %v", r, err)
		}
	}
}

func jpegSegment(marker byte, payload []byte) []byte {
	b := []byte{0xFF, marker, 0, 0}
	binary.BigEndian.PutUint16(b[2:], uint16(len(payload)+2))
	return append(b, payload...)
}

func TestJPEGMetadataLossless(t *testing.T) {
	var encoded bytes.Buffer
	if err := jpeg.Encode(&encoded, sampleImage(), nil); err != nil {
		t.Fatal(err)
	}
	base := encoded.Bytes()
	meta := jpegSegment(0xEB, []byte("JP\x00\x01\x00\x00\x00\x01jumb c2pa"))
	for _, offset := range []int{2, len(base) - 2} {
		input := append(append(bytes.Clone(base[:offset]), meta...), base[offset:]...)
		out, r, err := Process("photo.jpg", input, Options{})
		if err != nil {
			t.Fatal(err)
		}
		if !r.WouldChange || !bytes.Equal(out, base) {
			t.Fatalf("JPEG bytes changed: %+v", r)
		}
		if _, err := jpeg.Decode(bytes.NewReader(out)); err != nil {
			t.Fatal(err)
		}
	}
	comment := jpegSegment(0xFE, []byte("Claude Monet / Generated by ImageMagick"))
	input := append(append(bytes.Clone(base[:2]), comment...), base[2:]...)
	out, r, err := Process("photo.jpg", input, Options{})
	if err != nil || r.WouldChange || !bytes.Equal(out, input) {
		t.Fatal("benign comment changed", err)
	}
}

func riffChunk(typ string, p []byte) []byte {
	b := make([]byte, 8)
	copy(b, typ)
	binary.LittleEndian.PutUint32(b[4:], uint32(len(p)))
	b = append(b, p...)
	if len(p)%2 != 0 {
		b = append(b, 0)
	}
	return b
}

func TestWebPFlagsAndPayload(t *testing.T) {
	input := []byte("RIFF\x00\x00\x00\x00WEBP")
	input = append(input, riffChunk("VP8X", []byte{0x04, 0, 0, 0, 0, 0, 0, 0, 0, 0})...)
	imageChunk := riffChunk("VP8 ", []byte{1, 2, 3, 4})
	input = append(input, imageChunk...)
	input = append(input, riffChunk("XMP ", []byte("c2pa"))...)
	binary.LittleEndian.PutUint32(input[4:], uint32(len(input)-8))
	out, r, err := Process("photo.webp", input, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if !r.WouldChange || out[20] != 0 || int(binary.LittleEndian.Uint32(out[4:])) != len(out)-8 || !bytes.HasSuffix(out, imageChunk) {
		t.Fatalf("bad WebP rewrite: %x", out)
	}
	_, r, err = Process("photo.webp", out, Options{})
	if err != nil || r.WouldChange {
		t.Fatalf("not idempotent: %+v %v", r, err)
	}
}

func TestMalformedImages(t *testing.T) {
	var encoded bytes.Buffer
	png.Encode(&encoded, sampleImage())
	badCRC := bytes.Clone(encoded.Bytes())
	badCRC[29] ^= 1
	for _, data := range [][]byte{pngSignature, append(bytes.Clone(pngSignature), []byte{255, 255, 255, 255, 'I', 'D', 'A', 'T', 0, 0, 0, 0}...), badCRC, {0xFF, 0xD8, 0xFF, 0xE1, 0, 0}, []byte("RIFF\x04\x00\x00\x00WEBP")} {
		if _, _, err := Process("image", data, Options{}); err == nil {
			t.Fatalf("accepted malformed image: %x", data)
		}
	}
}
