package watermark

import (
	"strings"
	"testing"
)

func TestMetadataAndBody(t *testing.T) {
	tests := []struct{ name, input, want string }{
		{"note.md", "---\ntitle: Claude Monet\ngenerator: Claude\ndescription: A static site generator\n---\n# Body\u200b\r\n", "---\ntitle: Claude Monet\ndescription: A static site generator\n---\n# Body\r\n"},
		{"multi.md", "---\ntitle: Test\nprovenance:\n  model: OpenAI\n  version: 1\nauthor: Me\n---\nKeep", "---\ntitle: Test\nauthor: Me\n---\nKeep"},
		{"block.md", "---\ngenerator: |\n  Claude\ntitle: Keep\n---\nBody", "---\ntitle: Keep\n---\nBody"},
		{"page.html", `<html><head><meta name="generator" content="ChatGPT"><meta content="WordPress" name="generator"><meta name="description" content="Claude Monet"></head><body>Keep</body></html>`, `<html><head><meta content="WordPress" name="generator"><meta name="description" content="Claude Monet"></head><body>Keep</body></html>`},
		{"attr.html", `<META content='OpenAI > other' NAME=generator><p>Keep</p>`, `<p>Keep</p>`},
		{"script.html", `<script>const x = '<meta name="generator" content="Claude">';</script>`, `<script>const x = '<meta name="generator" content="Claude">';</script>`},
		{"art.svg", `<svg xmlns="http://www.w3.org/2000/svg"><metadata><ai>c2pa</ai></metadata><text>Claude Monet</text><rect width="2" height="2"/></svg>`, `<svg xmlns="http://www.w3.org/2000/svg"><text>Claude Monet</text><rect width="2" height="2"/></svg>`},
		{"example.md", "# Example\n```yaml\ngenerator: Claude\n```\n```html\n<meta name=generator content=Claude>\n```", "# Example\n```yaml\ngenerator: Claude\n```\n```html\n<meta name=generator content=Claude>\n```"},
		{"file.go", "package main\nconst a = `Generated by Claude`\n// \u200bcomment\n", "package main\nconst a = `Generated by Claude`\n// comment\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out, r, err := Process(tt.name, []byte(tt.input), Options{})
			if err != nil {
				t.Fatal(err)
			}
			if string(out) != tt.want {
				t.Fatalf("got %q want %q", out, tt.want)
			}
			if r.WouldChange != (tt.input != tt.want) {
				t.Fatal("mismatched result")
			}
		})
	}
}

func TestMalformedMarkupRefused(t *testing.T) {
	for name, input := range map[string]string{"broken.md": "---\na: [\n---\n", "broken.svg": "<svg><metadata>c2pa</svg>"} {
		if _, _, err := Process(name, []byte(input), Options{}); err == nil {
			t.Fatalf("accepted %s", name)
		}
	}
}

func TestMetadataAnchorNotBroken(t *testing.T) {
	input := "---\ngenerator: &tool Claude\ntitle: *tool\n---\nBody"
	if _, _, err := Process("note.md", []byte(input), Options{}); err == nil {
		t.Fatal("removed an anchor still referenced by a retained field")
	}
}

func TestSourceProseIsNotMetadata(t *testing.T) {
	input := "// OpenAI Claude SynthID C2PA\nconst x = \"\\u200b\";\n"
	out, r, err := Process("file.js", []byte(input), Options{})
	if err != nil || string(out) != input || len(r.Findings) != 0 {
		t.Fatalf("%s %+v %v", out, r, err)
	}
	_, hits := CleanText(strings.Repeat("x", 5), Options{})
	if len(hits) != 0 {
		t.Fatal(hits)
	}
}
